---
name: VyOS Rolling

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

env:
  VYOS_URL: https://github.com/vyos/vyos-build
  VYOS_BRANCH: sagitta
  VYOS_ARCH: amd64
  VYOS_BUILD_BY: autobuild-vyos@samipsolutions.fi
  VYOS_BUILD_TYPE: release
  VYOS_VERSION: 1.4-rolling
  VYOS_KERNEL_VERSION: v6.1.60

jobs:
  release:
    runs-on: buildjet-8vcpu-ubuntu-2204
    permissions:
      # Need permission to write to the Releases tab now.
      # https://github.com/ncipollo/release-action/issues/208.
      contents: write
    container:
      image: vyos/vyos-build:sagitta
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: custom-patches
          sparse-checkout: |
            patches
      - name: Generate Token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ env.VYOS_VERSION }}-${build_date}" >> "$GITHUB_OUTPUT"
          echo "iso-name=${{ env.VYOS_VERSION }}-${build_date}-${{ env.VYOS_ARCH }}" >> "$GITHUB_OUTPUT"

      - name: Clone vyos-build
        run: git clone -b ${{ env.VYOS_BRANCH }} --single-branch ${{ env.VYOS_URL }}

      - name: Download sops deb
        uses: robinraju/release-downloader@768b85c8d69164800db5fc00337ab917daf3ce68 # v1.7
        with:
          repository: mozilla/sops
          latest: true
          fileName: "*amd64.deb"
          out-file-path: vyos-build/packages

      - name: Copy custom patches to linux-kernel folder
        run: |
          cp -Rv custom-patches/ vyos-build/packages/linux-kernel/
          mv -v vyos-build/packages/linux-kernel/custom-patches/patches/linux-kernel/build-intel-ixgbe.sh vyos-build/packages/linux-kernel/

      - name: Fetch kernel sources
        working-directory: vyos-build/packages/linux-kernel
        run: git clone -b ${{ env.VYOS_KERNEL_VERSION }} --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

      - name: Restore cached kernel
        id: cache-kernel-restore
        uses: buildjet/cache/restore@v3
        with:
          path: |
            vyos-build/packages/linux-kernel/linux
          key: ${{ runner.os }}-${{ env.VYOS_KERNEL_VERSION }}

      - name: Compile kernel
        working-directory: vyos-build/packages/linux-kernel
        if: steps.cache-kernel-restore.outputs.cache-hit != 'true'
        run: |
          sudo ./build-kernel.sh

      - name: Save kernel to cache
        uses: buildjet/cache/save@v3
        id: kernel-cache
        with:
          path: |
           vyos-build/packages/linux-kernel/linux
          key: ${{ runner.os }}-${{ env.VYOS_KERNEL_VERSION }}

      - name: Compile ixgbe module
        working-directory: vyos-build/packages/linux-kernel
        run: |
          sudo ./build-intel-ixgbe.sh

      - name: Copy all debs to be installed
        run: |
          cp -Rv vyos-build/packages/linux-kernel/**.deb vyos-build/packages/

      - name: Configure
        working-directory: vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso \
              --architecture ${{ env.VYOS_ARCH }} \
              --build-by ${{ env.VYOS_BUILD_BY }} \
              --build-type ${{ env.VYOS_BUILD_TYPE }} \
              --build-comment "VyOS with additional packages" \
              --version ${{ steps.vars.outputs.tag-name }} \
              --custom-package "git" \
              --custom-package "iptables" \
              --custom-package "jo" \
              --custom-package "vim" \
              --custom-package "moreutils" \
              --custom-package "python3-venv" \
              --custom-package "tree"

      - name: Create release with artifact
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          tag: "v${{ steps.vars.outputs.tag-name }}"
          artifacts: "./vyos-build/build/vyos-${{ steps.vars.outputs.iso-name }}.iso"
          artifactErrorsFailBuild: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.4.html

      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 120
          delete_tags: true
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
